// Code generated by protoc-gen-go. DO NOT EDIT.
// source: keyValue.proto

/*
Package keyValue is a generated protocol buffer package.

It is generated from these files:
	keyValue.proto

It has these top-level messages:
	KeyValue
	Any
*/
package keyValue

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type KeyValue struct {
	Key   []byte `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *Any   `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *KeyValue) Reset()                    { *m = KeyValue{} }
func (m *KeyValue) String() string            { return proto.CompactTextString(m) }
func (*KeyValue) ProtoMessage()               {}
func (*KeyValue) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *KeyValue) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *KeyValue) GetValue() *Any {
	if m != nil {
		return m.Value
	}
	return nil
}

type Any struct {
	TypeUrl string `protobuf:"bytes,1,opt,name=TypeUrl" json:"TypeUrl,omitempty"`
	Value   []byte `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *Any) Reset()                    { *m = Any{} }
func (m *Any) String() string            { return proto.CompactTextString(m) }
func (*Any) ProtoMessage()               {}
func (*Any) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Any) GetTypeUrl() string {
	if m != nil {
		return m.TypeUrl
	}
	return ""
}

func (m *Any) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*KeyValue)(nil), "keyValue.KeyValue")
	proto.RegisterType((*Any)(nil), "keyValue.Any")
}

func init() { proto.RegisterFile("keyValue.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 123 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0xcb, 0x4e, 0xad, 0x0c,
	0x4b, 0xcc, 0x29, 0x4d, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x1c,
	0xb9, 0x38, 0xbc, 0xa1, 0x6c, 0x21, 0x01, 0x2e, 0x66, 0xa0, 0xb8, 0x04, 0xa3, 0x02, 0xa3, 0x06,
	0x4f, 0x10, 0x88, 0x29, 0xa4, 0xcc, 0xc5, 0x5a, 0x06, 0x92, 0x92, 0x60, 0x02, 0x8a, 0x71, 0x1b,
	0xf1, 0xea, 0xc1, 0xcd, 0x71, 0xcc, 0xab, 0x0c, 0x82, 0xc8, 0x29, 0x99, 0x72, 0x31, 0x03, 0x79,
	0x42, 0x12, 0x5c, 0xec, 0x21, 0x95, 0x05, 0xa9, 0xa1, 0x45, 0x39, 0x60, 0x13, 0x38, 0x83, 0x60,
	0x5c, 0x21, 0x11, 0x64, 0x53, 0x78, 0xa0, 0xda, 0x92, 0xd8, 0xc0, 0x4e, 0x31, 0x06, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x4e, 0x3b, 0xa8, 0x0f, 0x9c, 0x00, 0x00, 0x00,
}
