// Code generated by protoc-gen-go. DO NOT EDIT.
// source: storeStr.proto

/*
Package storeStr is a generated protocol buffer package.

It is generated from these files:
	storeStr.proto

It has these top-level messages:
	Triple
*/
package storeStr

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Triple struct {
	Row    string `protobuf:"bytes,1,opt,name=row" json:"row,omitempty"`
	Column string `protobuf:"bytes,2,opt,name=column" json:"column,omitempty"`
	Value  string `protobuf:"bytes,3,opt,name=value" json:"value,omitempty"`
}

func (m *Triple) Reset()                    { *m = Triple{} }
func (m *Triple) String() string            { return proto.CompactTextString(m) }
func (*Triple) ProtoMessage()               {}
func (*Triple) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Triple) GetRow() string {
	if m != nil {
		return m.Row
	}
	return ""
}

func (m *Triple) GetColumn() string {
	if m != nil {
		return m.Column
	}
	return ""
}

func (m *Triple) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*Triple)(nil), "storeStr.Triple")
}

func init() { proto.RegisterFile("storeStr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 105 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0x2e, 0xc9, 0x2f,
	0x4a, 0x0d, 0x2e, 0x29, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x3c,
	0xb8, 0xd8, 0x42, 0x8a, 0x32, 0x0b, 0x72, 0x52, 0x85, 0x04, 0xb8, 0x98, 0x8b, 0xf2, 0xcb, 0x25,
	0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x31, 0x2e, 0xb6, 0xe4, 0xfc, 0x9c, 0xd2,
	0xdc, 0x3c, 0x09, 0x26, 0xb0, 0x20, 0x94, 0x27, 0x24, 0xc2, 0xc5, 0x5a, 0x96, 0x98, 0x53, 0x9a,
	0x2a, 0xc1, 0x0c, 0x16, 0x86, 0x70, 0x92, 0xd8, 0xc0, 0x46, 0x1b, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x38, 0xed, 0xb7, 0x8f, 0x6c, 0x00, 0x00, 0x00,
}
